name: Android Build - Main Branch

on:
  push:
    branches: [ main ]

concurrency:
  group: build-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    name: Test & Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: |
          echo "Running all unit tests before building APK..."
          ./gradlew test --stacktrace

      - name: Build Debug APK
        if: success()
        run: |
          echo "Tests passed! Building Debug APK..."
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-main
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-main
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Build Summary
        if: success()
        run: |
          echo "✅ Build completed successfully!"
          echo ""
          echo "📦 APK Information:"
          ls -lh app/build/outputs/apk/debug/app-debug.apk
          echo ""
          echo "🎯 APK available in Artifacts section"
