name: Android CI - Quick Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ci-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Test Summary
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ All tests passed successfully!"
          else
            echo "❌ Some tests failed. Check logs above."
            exit 1
          fi
